## 1. 라이브러리 불러오기

In [1]:
# ============================================================
# 1. 라이브러리 불러오기
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 2. 데이터 경로 설정

In [2]:
# ============================================================
# 2. 데이터 경로 설정
# ============================================================

# UCI 유압 시스템 원본 데이터가 저장된 폴더 경로 설정
DATA_DIR = "../data/raw/uci_hydraulic/extracted"

# 설정한 데이터 폴더가 실제로 존재하는지 확인
print("데이터 폴더 존재 여부 :", os.path.exists(DATA_DIR))

데이터 폴더 존재 여부 : True

## 3. 원본 데이터 파일 확인

In [3]:
# ============================================================
# 3-1. 데이터 폴더 내 파일 목록 확인
# ============================================================

# 데이터 폴더 안에 어떤 파일들이 있는지 확인
file_list = os.listdir(DATA_DIR)

# 파일명을 보기 쉽게 정렬
file_list = sorted(file_list)

# 파일 목록 출력
print("파일 목록 :")
print(file_list)

파일 목록 :
['CE.txt', 'CP.txt', 'EPS1.txt', 'FS1.txt', 'FS2.txt', 'PS1.txt', 'PS2.txt', 'PS3.txt', 'PS4.txt', 'PS5.txt', 'PS6.txt', 'SE.txt', 'TS1.txt', 'TS2.txt', 'TS3.txt', 'TS4.txt', 'VS1.txt', 'description.txt', 'documentation.txt', 'profile.txt']

In [4]:
# ============================================================
# 3-2. 센서 파일 17개 목록 정의
# ============================================================

# 분석에 사용할 총 17개의 센서 파일명을 리스트로 정의
sensor_files = [
    "PS1.txt", "PS2.txt", "PS3.txt",
    "PS4.txt", "PS5.txt", "PS6.txt",
    "EPS1.txt",
    "FS1.txt", "FS2.txt",
    "TS1.txt", "TS2.txt", "TS3.txt", "TS4.txt",
    "VS1.txt",
    "CE.txt", "CP.txt", "SE.txt"
]

# 센서 파일 목록 출력
print("센서 파일 목록 :")
print(sensor_files)

센서 파일 목록 :
['PS1.txt', 'PS2.txt', 'PS3.txt', 'PS4.txt', 'PS5.txt', 'PS6.txt', 'EPS1.txt', 'FS1.txt', 'FS2.txt', 'TS1.txt', 'TS2.txt', 'TS3.txt', 'TS4.txt', 'VS1.txt', 'CE.txt', 'CP.txt', 'SE.txt']

In [5]:
# ============================================================
# 3-3. 센서 파일 개수 확인
# ============================================================

# 분석에 사용할 센서 파일이 총 17개인지 확인
print("센서 파일 개수 :", len(sensor_files))

센서 파일 개수 : 17

In [6]:
# ============================================================
# 3-4. profile.txt 존재 여부 확인
# ============================================================

# 정답 라벨이 저장된 profile.txt 파일의 전체 경로 생성
profile_path = os.path.join(DATA_DIR, "profile.txt")

# profile.txt 파일이 실제 데이터 폴더에 존재하는지 확인
print("profile.txt 존재 여부 :", os.path.exists(profile_path))

profile.txt 존재 여부 : True

## 4. 센서 데이터 사이클 수 검사

In [7]:
# ============================================================
# 4-1. 센서 17개 데이터 불러오기
# ============================================================

# 센서별 DataFrame을 저장할 딕셔너리 생성
# key   : 센서 파일명
# value : 해당 센서의 데이터
sensor_data = {}

# 3-2에서 정의한 sensor_files의 파일을 하나씩 불러오기
for file_name in sensor_files:

    # 데이터 폴더 경로와 파일명을 결합하여 전체 파일 경로 생성
    file_path = os.path.join(DATA_DIR, file_name)

    # 센서 데이터는 공백으로 값이 구분되어 있으며
    # 컬럼명이 존재하지 않으므로 header=None으로 불러옴
    sensor_data[file_name] = pd.read_csv(
        file_path,
        sep=r"\s+",
        header=None
    )

# 정상적으로 17개의 센서가 불러와졌는지 확인
print("불러온 센서 파일 개수 :", len(sensor_data))

불러온 센서 파일 개수 : 17

In [8]:
# ============================================================
# 4-2. 센서별 사이클 수 확인
# ============================================================

# UCI 유압 시스템 데이터의 전체 운전 사이클 수
EXPECTED_CYCLES = 2205

# 센서별 사이클 수를 저장할 리스트
cycle_results = []

# 불러온 17개 센서의 사이클 수 확인
for file_name, df in sensor_data.items():

    # DataFrame의 행 개수는 운전 사이클의 개수를 의미
    cycle_count = df.shape[0]

    # 사이클 수가 기준인 2,205개와 같은지 확인
    if cycle_count == EXPECTED_CYCLES:
        status = "정상"
    else:
        status = "확인 필요"

    # 확인 결과 저장
    cycle_results.append({
        "센서 파일": file_name,
        "사이클 수": cycle_count,
        "검사 결과": status
    })

# 결과를 DataFrame으로 변환
cycle_check_df = pd.DataFrame(cycle_results)

# 센서별 사이클 수 출력
display(cycle_check_df)

       센서 파일  사이클 수 검사 결과
0    PS1.txt   2205    정상
1    PS2.txt   2205    정상
2    PS3.txt   2205    정상
3    PS4.txt   2205    정상
4    PS5.txt   2205    정상
5    PS6.txt   2205    정상
6   EPS1.txt   2205    정상
7    FS1.txt   2205    정상
8    FS2.txt   2205    정상
9    TS1.txt   2205    정상
10   TS2.txt   2205    정상
11   TS3.txt   2205    정상
12   TS4.txt   2205    정상
13   VS1.txt   2205    정상
14    CE.txt   2205    정상
15    CP.txt   2205    정상
16    SE.txt   2205    정상

In [9]:
# ============================================================
# 4-3. 센서별 사이클당 데이터 수 확인
# ============================================================

# 센서별 한 사이클당 측정값 개수를 저장할 리스트
sample_results = []

# 각 센서 DataFrame의 열 개수 확인
for file_name, df in sensor_data.items():

    # 열 개수는 하나의 60초 운전 사이클 동안
    # 해당 센서가 측정한 데이터 개수를 의미
    values_per_cycle = df.shape[1]

    # 결과 저장
    sample_results.append({
        "센서 파일": file_name,
        "사이클당 데이터 수": values_per_cycle
    })

# 결과를 DataFrame으로 변환
sample_check_df = pd.DataFrame(sample_results)

# 센서별 측정 데이터 개수 확인
display(sample_check_df)

       센서 파일  사이클당 데이터 수
0    PS1.txt        6000
1    PS2.txt        6000
2    PS3.txt        6000
3    PS4.txt        6000
4    PS5.txt        6000
5    PS6.txt        6000
6   EPS1.txt        6000
7    FS1.txt         600
8    FS2.txt         600
9    TS1.txt          60
10   TS2.txt          60
11   TS3.txt          60
12   TS4.txt          60
13   VS1.txt          60
14    CE.txt          60
15    CP.txt          60
16    SE.txt          60

In [10]:
# ============================================================
# 4-4. profile.txt 사이클 수 확인
# ============================================================

# 3-4에서 생성한 profile_path를 이용하여
# 정답 라벨 파일인 profile.txt 불러오기
profile_df = pd.read_csv(
    profile_path,
    sep=r"\s+",
    header=None
)

# profile.txt의 행 개수
# → 전체 운전 사이클 수
profile_cycle_count = profile_df.shape[0]

# profile.txt의 열 개수
# → 정답 라벨의 개수
profile_label_count = profile_df.shape[1]

print("profile.txt 사이클 수 :", profile_cycle_count)
print("profile.txt 라벨 수   :", profile_label_count)

profile.txt 사이클 수 : 2205
profile.txt 라벨 수   : 5

In [11]:
# ============================================================
# 4-5. 전체 사이클 검사 결과 확인
# ============================================================

# 17개 센서 파일의 사이클 수가
# 모두 2,205개인지 확인
all_sensor_normal = (
    cycle_check_df["사이클 수"] == EXPECTED_CYCLES
).all()

# profile.txt 역시 2,205개인지 확인
profile_normal = (
    profile_cycle_count == EXPECTED_CYCLES
)

# 센서 파일과 profile.txt가 모두 정상인지 최종 확인
if all_sensor_normal and profile_normal:
    print("검사 완료 : 센서 17개 파일과 profile.txt 모두 2,205개 사이클입니다.")
else:
    print("확인 필요 : 사이클 수가 다른 파일이 존재합니다.")

검사 완료 : 센서 17개 파일과 profile.txt 모두 2,205개 사이클입니다.

## 5. 센서 정보 정의

In [12]:
# ============================================================
# 5-1. 센서명 정의
# ============================================================

# UCI 유압 시스템 데이터에서 사용하는
# 총 17개의 센서명을 정의
sensor_names = [
    "PS1", "PS2", "PS3",
    "PS4", "PS5", "PS6",
    "EPS1",
    "FS1", "FS2",
    "TS1", "TS2", "TS3", "TS4",
    "VS1",
    "CE", "CP", "SE"
]

# 센서명 목록 출력
print("센서명 목록 :")
print(sensor_names)

센서명 목록 :
['PS1', 'PS2', 'PS3', 'PS4', 'PS5', 'PS6', 'EPS1', 'FS1', 'FS2', 'TS1', 'TS2', 'TS3', 'TS4', 'VS1', 'CE', 'CP', 'SE']

In [13]:
# ============================================================
# 5-2. 센서별 물리량 정의
# ============================================================

# 각 센서가 측정하는 물리량을 정의
#
# PS  : 압력
# EPS : 모터 전력
# FS  : 유량
# TS  : 온도
# VS  : 진동
# CE  : 냉각 효율
# CP  : 냉각 출력
# SE  : 효율 계수

sensor_types = {
    "PS1": "압력",
    "PS2": "압력",
    "PS3": "압력",
    "PS4": "압력",
    "PS5": "압력",
    "PS6": "압력",

    "EPS1": "모터 전력",

    "FS1": "유량",
    "FS2": "유량",

    "TS1": "온도",
    "TS2": "온도",
    "TS3": "온도",
    "TS4": "온도",

    "VS1": "진동",

    "CE": "냉각 효율",
    "CP": "냉각 출력",
    "SE": "효율 계수"
}

# 센서별 물리량 출력
print("센서별 물리량 :")
print(sensor_types)

센서별 물리량 :
{'PS1': '압력', 'PS2': '압력', 'PS3': '압력', 'PS4': '압력', 'PS5': '압력', 'PS6': '압력', 'EPS1': '모터 전력', 'FS1': '유량', 'FS2': '유량', 'TS1': '온도', 'TS2': '온도', 'TS3': '온도', 'TS4': '온도', 'VS1': '진동', 'CE': '냉각 효율', 'CP': '냉각 출력', 'SE': '효율 계수'}

In [14]:
# ============================================================
# 5-3. 원본 문서에서 센서 단위 확인
# ============================================================

# UCI 데이터와 함께 제공된 documentation.txt 경로 생성
documentation_path = os.path.join(DATA_DIR, "documentation.txt")

# 원본 문서의 문자 인코딩에 맞춰 cp1252로 파일 읽기
# 특수문자와 유럽권 문자가 깨지는 현상을 방지
with open(
    documentation_path,
    "r",
    encoding="cp1252"
) as file:
    documentation_text = file.read()

# 원본 문서 내용 출력
print("documentation.txt 내용 :")
print(documentation_text)

documentation.txt 내용 :
1. Title: Condition monitoring of hydraulic systems

2. Source Information
   -- Creator: Nikolai Helwig, ZeMA gGmbH, Eschberger Weg 46, 66121 Saarbrücken
   -- Donors (with approval from creator): M. Bastuck (m.bastuck@lmt.uni-saarland.de), T. Schneider (t.schneider@zema.de)
   -- Date: April, 2018

3. Past Usage:
   [1] Nikolai Helwig, Eliseo Pignanelli, Andreas Schütze, ‘Condition Monitoring of a Complex Hydraulic System Using Multivariate Statistics’, in Proc. I2MTC-2015 - 2015 IEEE International Instrumentation and Measurement Technology Conference, paper PPS1-39, Pisa, Italy, May 11-14, 2015. doi: 10.1109/I2MTC.2015.7151267
      -- detailed description of data and measurement setup
      -- automated feature extraction via Pearson correlation and comparison of several classification algorithms
      -- Cooler and Valve states are "easy" targets (perfect classification achieved), Pump and especially Accumulator states are more complex targets

   [2] N. Helwig, A. Schütze, ‘Detecting and compensating sensor faults in a hydraulic condition monitoring system’, in Proc. SENSOR 2015 - 17th International Conference on Sensors and Measurement Technology, oral presentation D8.1, Nuremberg, Germany, May 19-21, 2015. doi: 10.5162/sensor2015/D8.1
      -- sensor drift and offset can be compensated by the automatic feature extraction described in [1]
      -- faults of up to 5 sensors can be compensated for

   [3] Tizian Schneider, Nikolai Helwig, Andreas Schütze, ‘Automatic feature extraction and selection for classification of cyclical time series data’, tm - Technisches Messen (2017), 84(3), 198–206. doi: 10.1515/teme-2016-0072
      -- one of several example datasets for automatic feature extraction
      -- with ALA and RFESVM the error rate was reduced to 0.35 % (from 9.6 % in [1]) for the hydraulic accumulator state classification

4. Relevant Information:
   -- The data set was experimentally obtained with a hydraulic test rig. This test rig consists of a primary working and a secondary cooling-filtration circuit which are connected via the oil tank [1], [2]. The system cyclically repeats constant load cycles (duration 60 seconds) and measures process values such as pressures, volume flows and temperatures while the condition of four hydraulic components (cooler, valve, pump and accumulator) is quantitatively varied.

5. Number of Instances: 2205

6. Number of Attributes: 43680 (8x60 (1 Hz) + 2x600 (10 Hz) + 7x6000 (100 Hz))

7. Attribute Information:
   Attributes are sensor data (all numeric and continuous) from measurements taken at the same point in time, respectively, of a hydraulic test rig's working cycle.
   The sensors were read with different sampling rates, leading to different numbers of attributes per sensor despite they were all exposed to the same working cycle.

   1. Pressure sensors (PS1-6): 100 Hz, 6000 attributes per sensor (6 sensors)
   2. Motor power sensor (EPS1): 100 Hz, 6000 attributes per sensor (1 sensor)
   3. Volume flow sensors (FS1/2): 10 Hz, 600 attributes per sensor (2 sensors)
   4. Temperature sensors (TS1-4): 1 Hz, 60 attributes per sensor (4 sensors)
   5. Vibration sensor (VS1): 1 Hz, 60 attributes per sensor (1 sensor)
   6. Efficiency factor (SE): 1 Hz, 60 attributes per sensor (1 sensor)
   7. Virtual cooling efficiency sensor (CE): 1 Hz, 60 attributes per sensor (1 sensor)
   8. Virtual cooling power sensor (CP): 1 Hz, 60 attributes per sensor (1 sensor)

8. Missing Attribute Values: None

9. Class Distribution: there are 5 different class value vectors provided in profile.txt.
   All but number 5 (stable flag) describe degradation processes over time and, thus, their values do not represent distinct categories, but continuous values.

   1. Cooler condition / %:
      3: close to total failure (732 instances)
      20: reduced effifiency (732 instances)
      100: full efficiency (741 instances)

   2. Valve condition / %:
      100: optimal switching behavior (1125 instances)
      90: small lag (360 instances)
      80: severe lag (360 instances)
      73: close to total failure (360 instances)

   3. Internal pump leakage:
      0: no leakage (1221 instances)
      1: weak leakage (492 instances)
      2: severe leakage (492 instances)

   4. Hydraulic accumulator / bar:
      130: optimal pressure (599 instances)
      115: slightly reduced pressure (399 instances)
      100: severely reduced pressure (399 instances)
      90: close to total failure (808 instances)

   5. stable flag:
      0: conditions were stable (1449 instances)
      1: static conditions might not have been reached yet (756 instances)

In [15]:
# ============================================================
# 5-4. 센서별 단위 정의
# ============================================================

# documentation.txt에는 각 센서의 측정 단위가 명시되어 있지 않음
# 따라서 추정값을 사용하지 않고 "문서 미기재"로 기록
sensor_units = {
    "PS1": "문서 미기재",
    "PS2": "문서 미기재",
    "PS3": "문서 미기재",
    "PS4": "문서 미기재",
    "PS5": "문서 미기재",
    "PS6": "문서 미기재",

    "EPS1": "문서 미기재",

    "FS1": "문서 미기재",
    "FS2": "문서 미기재",

    "TS1": "문서 미기재",
    "TS2": "문서 미기재",
    "TS3": "문서 미기재",
    "TS4": "문서 미기재",

    "VS1": "문서 미기재",

    "CE": "문서 미기재",
    "CP": "문서 미기재",
    "SE": "문서 미기재"
}

# 센서별 단위 출력
print("센서별 단위 :")
print(sensor_units)

센서별 단위 :
{'PS1': '문서 미기재', 'PS2': '문서 미기재', 'PS3': '문서 미기재', 'PS4': '문서 미기재', 'PS5': '문서 미기재', 'PS6': '문서 미기재', 'EPS1': '문서 미기재', 'FS1': '문서 미기재', 'FS2': '문서 미기재', 'TS1': '문서 미기재', 'TS2': '문서 미기재', 'TS3': '문서 미기재', 'TS4': '문서 미기재', 'VS1': '문서 미기재', 'CE': '문서 미기재', 'CP': '문서 미기재', 'SE': '문서 미기재'}

In [16]:
# ============================================================
# 5-5. 센서별 샘플링 속도 정의
# ============================================================

# documentation.txt에 명시된 센서별 샘플링 속도 정의
#
# PS1 ~ PS6 : 100 Hz
# EPS1      : 100 Hz
# FS1 ~ FS2 : 10 Hz
# TS1 ~ TS4 : 1 Hz
# VS1       : 1 Hz
# CE        : 1 Hz
# CP        : 1 Hz
# SE        : 1 Hz

sensor_sampling_rates = {
    "PS1": 100,
    "PS2": 100,
    "PS3": 100,
    "PS4": 100,
    "PS5": 100,
    "PS6": 100,

    "EPS1": 100,

    "FS1": 10,
    "FS2": 10,

    "TS1": 1,
    "TS2": 1,
    "TS3": 1,
    "TS4": 1,

    "VS1": 1,

    "CE": 1,
    "CP": 1,
    "SE": 1
}

# 센서별 샘플링 속도 출력
print("센서별 샘플링 속도(Hz) :")
print(sensor_sampling_rates)

센서별 샘플링 속도(Hz) :
{'PS1': 100, 'PS2': 100, 'PS3': 100, 'PS4': 100, 'PS5': 100, 'PS6': 100, 'EPS1': 100, 'FS1': 10, 'FS2': 10, 'TS1': 1, 'TS2': 1, 'TS3': 1, 'TS4': 1, 'VS1': 1, 'CE': 1, 'CP': 1, 'SE': 1}

In [17]:
# ============================================================
# 5-6. 센서별 사이클당 측정값 수 정의
# ============================================================

# 한 운전 사이클은 60초
#
# 100 Hz × 60초 = 6,000개
# 10 Hz  × 60초 =   600개
# 1 Hz   × 60초 =    60개

sensor_values_per_cycle = {
    "PS1": 6000,
    "PS2": 6000,
    "PS3": 6000,
    "PS4": 6000,
    "PS5": 6000,
    "PS6": 6000,

    "EPS1": 6000,

    "FS1": 600,
    "FS2": 600,

    "TS1": 60,
    "TS2": 60,
    "TS3": 60,
    "TS4": 60,

    "VS1": 60,

    "CE": 60,
    "CP": 60,
    "SE": 60
}

# 센서별 사이클당 측정값 수 출력
print("센서별 사이클당 측정값 수 :")
print(sensor_values_per_cycle)

센서별 사이클당 측정값 수 :
{'PS1': 6000, 'PS2': 6000, 'PS3': 6000, 'PS4': 6000, 'PS5': 6000, 'PS6': 6000, 'EPS1': 6000, 'FS1': 600, 'FS2': 600, 'TS1': 60, 'TS2': 60, 'TS3': 60, 'TS4': 60, 'VS1': 60, 'CE': 60, 'CP': 60, 'SE': 60}

In [18]:
# ============================================================
# 5-7. 센서 정보표 생성
# ============================================================

# 지금까지 정의한 센서 정보를 하나의 표로 정리
#
# 컬럼 구성
# - 센서명
# - 물리량
# - 단위
# - 샘플링 속도(Hz)
# - 사이클당 측정값 수

sensor_info_df = pd.DataFrame({
    "센서명": sensor_names,
    "물리량": [sensor_types[sensor] for sensor in sensor_names],
    "단위": [sensor_units[sensor] for sensor in sensor_names],
    "샘플링 속도(Hz)": [
        sensor_sampling_rates[sensor]
        for sensor in sensor_names
    ],
    "사이클당 측정값 수": [
        sensor_values_per_cycle[sensor]
        for sensor in sensor_names
    ]
})

# 센서 정보표 출력
print("센서 정보표 :")
display(sensor_info_df)

센서 정보표 :

     센서명    물리량      단위  샘플링 속도(Hz)  사이클당 측정값 수
0    PS1     압력  문서 미기재         100        6000
1    PS2     압력  문서 미기재         100        6000
2    PS3     압력  문서 미기재         100        6000
3    PS4     압력  문서 미기재         100        6000
4    PS5     압력  문서 미기재         100        6000
5    PS6     압력  문서 미기재         100        6000
6   EPS1  모터 전력  문서 미기재         100        6000
7    FS1     유량  문서 미기재          10         600
8    FS2     유량  문서 미기재          10         600
9    TS1     온도  문서 미기재           1          60
10   TS2     온도  문서 미기재           1          60
11   TS3     온도  문서 미기재           1          60
12   TS4     온도  문서 미기재           1          60
13   VS1     진동  문서 미기재           1          60
14    CE  냉각 효율  문서 미기재           1          60
15    CP  냉각 출력  문서 미기재           1          60
16    SE  효율 계수  문서 미기재           1          60

## 6. profile.txt 라벨 구조 확인

In [19]:
# ============================================================
# 6-1. profile.txt 불러오기
# ============================================================

# 각 운전 사이클의 정답 라벨이 저장된
# profile.txt 파일을 DataFrame으로 불러오기
#
# 데이터는 공백으로 구분되어 있으며
# 원본 파일에는 컬럼명이 없으므로 header=None 사용

profile_df = pd.read_csv(
    profile_path,
    sep=r"\s+",
    header=None
)

# profile.txt 데이터 크기 출력
print("profile.txt 데이터 크기 :")
print(profile_df.shape)

profile.txt 데이터 크기 :
(2205, 5)

In [20]:
# ============================================================
# 6-2. profile.txt 라벨 컬럼명 지정
# ============================================================

# documentation.txt에 기록된 순서에 따라
# profile.txt의 5개 라벨 컬럼에 이름을 지정
#
# cooler      : 냉각기 상태
# valve       : 밸브 상태
# pump        : 펌프 내부 누설 상태
# accumulator : 축압기 상태
# stable_flag : 측정 조건 안정 상태

profile_df.columns = [
    "cooler",
    "valve",
    "pump",
    "accumulator",
    "stable_flag"
]

# 지정된 컬럼명 출력
print("profile.txt 라벨 컬럼 :")
print(profile_df.columns.tolist())

profile.txt 라벨 컬럼 :
['cooler', 'valve', 'pump', 'accumulator', 'stable_flag']

In [21]:
# ============================================================
# 6-3. profile.txt 라벨 데이터 일부 확인
# ============================================================

# profile.txt의 앞 5개 데이터를 확인하여
# 각 라벨 컬럼에 값이 정상적으로 들어왔는지 확인

print("profile.txt 라벨 데이터 :")
display(profile_df.head())

profile.txt 라벨 데이터 :

   cooler  valve  pump  accumulator  stable_flag
0       3    100     0          130            1
1       3    100     0          130            1
2       3    100     0          130            1
3       3    100     0          130            1
4       3    100     0          130            1

In [22]:
# ============================================================
# 6-4. profile.txt 라벨 결측값 확인
# ============================================================

# 각 라벨 컬럼에 결측값이 존재하는지 확인
# isnull()  : 값이 비어 있는지 검사
# sum()     : 컬럼별 결측값 개수 계산

missing_values = profile_df.isnull().sum()

# 라벨별 결측값 개수 출력
print("라벨별 결측값 개수 :")
print(missing_values)

라벨별 결측값 개수 :
cooler         0
valve          0
pump           0
accumulator    0
stable_flag    0
dtype: int64

## 7. 라벨별 상태 코드 및 의미 정의

In [23]:
# ============================================================
# 7-1. 냉각기 상태 코드 및 의미 정의
# ============================================================

# documentation.txt의 Cooler condition 기준
#
# 3   : 거의 완전 고장 상태
# 20  : 효율 저하 상태
# 100 : 정상 효율 상태

cooler_labels = {
    3: "고장 근접",
    20: "효율 저하",
    100: "정상"
}

# 실제 profile.txt에 존재하는 냉각기 상태 코드 확인
print("냉각기 실제 상태 코드 :")
print(sorted(profile_df["cooler"].unique()))

# 상태 코드별 의미 출력
print("냉각기 상태 의미 :")
print(cooler_labels)

냉각기 실제 상태 코드 :
[np.int64(3), np.int64(20), np.int64(100)]
냉각기 상태 의미 :
{3: '고장 근접', 20: '효율 저하', 100: '정상'}

In [24]:
# ============================================================
# 7-2. 밸브 상태 코드 및 의미 정의
# ============================================================

# documentation.txt의 Valve condition 기준
#
# 73  : 거의 완전 고장 상태
# 80  : 심각한 동작 지연
# 90  : 약한 동작 지연
# 100 : 정상 동작 상태

valve_labels = {
    73: "고장 근접",
    80: "심각한 동작 지연",
    90: "약한 동작 지연",
    100: "정상"
}

# 실제 profile.txt에 존재하는 밸브 상태 코드 확인
print("밸브 실제 상태 코드 :")
print(sorted(profile_df["valve"].unique()))

# 상태 코드별 의미 출력
print("밸브 상태 의미 :")
print(valve_labels)

밸브 실제 상태 코드 :
[np.int64(73), np.int64(80), np.int64(90), np.int64(100)]
밸브 상태 의미 :
{73: '고장 근접', 80: '심각한 동작 지연', 90: '약한 동작 지연', 100: '정상'}

In [25]:
# ============================================================
# 7-3. 펌프 상태 코드 및 의미 정의
# ============================================================

# documentation.txt의 Internal pump leakage 기준
#
# 0 : 누설 없음
# 1 : 약한 누설
# 2 : 심각한 누설

pump_labels = {
    0: "누설 없음",
    1: "약한 누설",
    2: "심각한 누설"
}

# 실제 profile.txt에 존재하는 펌프 상태 코드 확인
print("펌프 실제 상태 코드 :")
print(sorted(profile_df["pump"].unique()))

# 상태 코드별 의미 출력
print("펌프 상태 의미 :")
print(pump_labels)

펌프 실제 상태 코드 :
[np.int64(0), np.int64(1), np.int64(2)]
펌프 상태 의미 :
{0: '누설 없음', 1: '약한 누설', 2: '심각한 누설'}

In [26]:
# ============================================================
# 7-4. 축압기 상태 코드 및 의미 정의
# ============================================================

# documentation.txt의 Hydraulic accumulator 기준
#
# 90  : 거의 완전 고장 상태
# 100 : 압력이 심각하게 감소한 상태
# 115 : 압력이 약간 감소한 상태
# 130 : 정상 압력 상태

accumulator_labels = {
    90: "고장 근접",
    100: "압력 심각 저하",
    115: "압력 약간 저하",
    130: "정상"
}

# 실제 profile.txt에 존재하는 축압기 상태 코드 확인
print("축압기 실제 상태 코드 :")
print(sorted(profile_df["accumulator"].unique()))

# 상태 코드별 의미 출력
print("축압기 상태 의미 :")
print(accumulator_labels)

축압기 실제 상태 코드 :
[np.int64(90), np.int64(100), np.int64(115), np.int64(130)]
축압기 상태 의미 :
{90: '고장 근접', 100: '압력 심각 저하', 115: '압력 약간 저하', 130: '정상'}

In [27]:
# ============================================================
# 7-5. 안정 상태 코드 및 의미 정의
# ============================================================

# documentation.txt의 stable flag 기준
#
# 0 : 측정 조건이 안정된 상태
# 1 : 아직 안정 상태에 도달하지 않았을 가능성이 있는 상태

stable_labels = {
    0: "안정",
    1: "미안정 가능"
}

# 실제 profile.txt에 존재하는 안정 상태 코드 확인
print("안정 상태 실제 코드 :")
print(sorted(profile_df["stable_flag"].unique()))

# 상태 코드별 의미 출력
print("안정 상태 의미 :")
print(stable_labels)

안정 상태 실제 코드 :
[np.int64(0), np.int64(1)]
안정 상태 의미 :
{0: '안정', 1: '미안정 가능'}

## 8. 라벨 클래스 분포 확인

In [28]:
# ============================================================
# 8-1. 냉각기 클래스 분포 확인
# ============================================================

# 냉각기 상태 코드별 데이터 개수 계산
cooler_counts = (
    profile_df["cooler"]
    .value_counts()
    .sort_index()
)

# 상태 코드별 의미와 데이터 개수를 표로 정리
cooler_distribution = pd.DataFrame({
    "상태 코드": cooler_counts.index,
    "상태": [
        cooler_labels[code]
        for code in cooler_counts.index
    ],
    "데이터 개수": cooler_counts.values
})

# 전체 데이터에서 각 상태가 차지하는 비율 계산
cooler_distribution["비율(%)"] = (
    cooler_distribution["데이터 개수"]
    / len(profile_df)
    * 100
).round(2)

# 냉각기 클래스 분포 출력
print("냉각기 클래스 분포 :")
display(cooler_distribution)

냉각기 클래스 분포 :

   상태 코드     상태  데이터 개수  비율(%)
0      3  고장 근접     732  33.20
1     20  효율 저하     732  33.20
2    100     정상     741  33.61

In [29]:
# ============================================================
# 8-2. 밸브 클래스 분포 확인
# ============================================================

# 밸브 상태 코드별 데이터 개수 계산
valve_counts = (
    profile_df["valve"]
    .value_counts()
    .sort_index()
)

# 상태 코드별 의미와 데이터 개수를 표로 정리
valve_distribution = pd.DataFrame({
    "상태 코드": valve_counts.index,
    "상태": [
        valve_labels[code]
        for code in valve_counts.index
    ],
    "데이터 개수": valve_counts.values
})

# 전체 데이터에서 각 상태가 차지하는 비율 계산
valve_distribution["비율(%)"] = (
    valve_distribution["데이터 개수"]
    / len(profile_df)
    * 100
).round(2)

# 밸브 클래스 분포 출력
print("밸브 클래스 분포 :")
display(valve_distribution)

밸브 클래스 분포 :

   상태 코드         상태  데이터 개수  비율(%)
0     73      고장 근접     360  16.33
1     80  심각한 동작 지연     360  16.33
2     90   약한 동작 지연     360  16.33
3    100         정상    1125  51.02

In [30]:
# ============================================================
# 8-3. 펌프 클래스 분포 확인
# ============================================================

# 펌프 상태 코드별 데이터 개수 계산
pump_counts = (
    profile_df["pump"]
    .value_counts()
    .sort_index()
)

# 상태 코드별 의미와 데이터 개수를 표로 정리
pump_distribution = pd.DataFrame({
    "상태 코드": pump_counts.index,
    "상태": [
        pump_labels[code]
        for code in pump_counts.index
    ],
    "데이터 개수": pump_counts.values
})

# 전체 데이터에서 각 상태가 차지하는 비율 계산
pump_distribution["비율(%)"] = (
    pump_distribution["데이터 개수"]
    / len(profile_df)
    * 100
).round(2)

# 펌프 클래스 분포 출력
print("펌프 클래스 분포 :")
display(pump_distribution)

펌프 클래스 분포 :

   상태 코드      상태  데이터 개수  비율(%)
0      0   누설 없음    1221  55.37
1      1   약한 누설     492  22.31
2      2  심각한 누설     492  22.31

In [31]:
# ============================================================
# 8-4. 축압기 클래스 분포 확인
# ============================================================

# 축압기 상태 코드별 데이터 개수 계산
accumulator_counts = (
    profile_df["accumulator"]
    .value_counts()
    .sort_index()
)

# 상태 코드별 의미와 데이터 개수를 표로 정리
accumulator_distribution = pd.DataFrame({
    "상태 코드": accumulator_counts.index,
    "상태": [
        accumulator_labels[code]
        for code in accumulator_counts.index
    ],
    "데이터 개수": accumulator_counts.values
})

# 전체 데이터에서 각 상태가 차지하는 비율 계산
accumulator_distribution["비율(%)"] = (
    accumulator_distribution["데이터 개수"]
    / len(profile_df)
    * 100
).round(2)

# 축압기 클래스 분포 출력
print("축압기 클래스 분포 :")
display(accumulator_distribution)

축압기 클래스 분포 :

   상태 코드        상태  데이터 개수  비율(%)
0     90     고장 근접     808  36.64
1    100  압력 심각 저하     399  18.10
2    115  압력 약간 저하     399  18.10
3    130        정상     599  27.17

In [32]:
# ============================================================
# 8-5. 안정 상태 클래스 분포 확인
# ============================================================

# 안정 상태 코드별 데이터 개수 계산
stable_counts = (
    profile_df["stable_flag"]
    .value_counts()
    .sort_index()
)

# 상태 코드별 의미와 데이터 개수를 표로 정리
stable_distribution = pd.DataFrame({
    "상태 코드": stable_counts.index,
    "상태": [
        stable_labels[code]
        for code in stable_counts.index
    ],
    "데이터 개수": stable_counts.values
})

# 전체 데이터에서 각 상태가 차지하는 비율 계산
stable_distribution["비율(%)"] = (
    stable_distribution["데이터 개수"]
    / len(profile_df)
    * 100
).round(2)

# 안정 상태 클래스 분포 출력
print("안정 상태 클래스 분포 :")
display(stable_distribution)

안정 상태 클래스 분포 :

   상태 코드      상태  데이터 개수  비율(%)
0      0      안정    1449  65.71
1      1  미안정 가능     756  34.29

In [33]:
# ============================================================
# 8-6. 전체 라벨 클래스 분포 요약
# ============================================================

# 각 라벨별 클래스 개수와 전체 데이터 수를 정리
label_summary_df = pd.DataFrame({
    "라벨": [
        "냉각기",
        "밸브",
        "펌프",
        "축압기",
        "안정 상태"
    ],
    "클래스 수": [
        profile_df["cooler"].nunique(),
        profile_df["valve"].nunique(),
        profile_df["pump"].nunique(),
        profile_df["accumulator"].nunique(),
        profile_df["stable_flag"].nunique()
    ],
    "전체 데이터 수": [
        profile_df["cooler"].count(),
        profile_df["valve"].count(),
        profile_df["pump"].count(),
        profile_df["accumulator"].count(),
        profile_df["stable_flag"].count()
    ]
})

# 전체 라벨 분포 요약표 출력
print("전체 라벨 클래스 분포 요약 :")
display(label_summary_df)

전체 라벨 클래스 분포 요약 :

      라벨  클래스 수  전체 데이터 수
0    냉각기      3      2205
1     밸브      4      2205
2     펌프      3      2205
3    축압기      4      2205
4  안정 상태      2      2205